
name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      #  .env を生成
      - name: Create .env file
        run: echo "${{ secrets.APP_ENV }}" > app/.env

      #  Angular build
      - name: Install and Build
        run: cat .env && npm ci && npm run build
        working-directory: app

      #  Deploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PERSONAL_ANALYSIS_B48E8 }}
          channelId: live
          projectId: personal-analysis-b48e8
